production:
  environment: production
  required_context: [ci, deliverybot/promoted]
  production_environment: true

staging:
  auto_deploy_on: refs/heads/production
  environment: staging
  production_environment: false

review:
  environment: pr${{ pr }}
  transient_environment: true
  production_environment: false
