image: cticti/aws-cli:node-ionic-alpine

pipelines:
  branches:
    v4-production:
    - step:
        caches:
          - node
        script:
          - npm i
          - ionic build --prod
          - aws s3 sync www/ s3://apspace-production/ --acl public-read
    v4-staging:
    - step:
        caches:
          - node
        script:
          - npm i
          - ionic build --prod
          - aws s3 sync www/ s3://apspace-staging/ --acl public-read