image: node:dubnium-alpine
pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn install
          - yarn lint
            # - yarn test --single-run --no-progress --browsers FirefoxHeadless
          - yarn build --aot
