image: cticti/aws-cli:node-10-ionic-alpine

pipelines:
  branches:
    production:
    - step:
        caches:
          - node
        script:
          - npm i
          - ionic cordova build browser --prod
          - aws s3 sync www/ s3://apspace-production/ --acl public-read
          - aws cloudfront create-invalidation --distribution-id E2U0MAK0TADMRA --paths "/*"

    staging:
    - step:
        caches:
          - node
        script:
          - npm i
          - ionic cordova build browser --prod
          - aws s3 sync www/ s3://apspace-staging/ --acl public-read
