image: beevelop/ionic:latest

pipelines:
  branches:
    production:
    - step:
        script:
          - npm install
          - ionic cordova build browser --prod
          - apt-get update
          - apt-get install -y software-properties-common
          - add-apt-repository ppa:deadsnakes/ppa
          - apt-get update
          - apt-get install -y python3.6 python3-pip
          - python3.6 -m pip install awscli --upgrade --user
          - export PATH=~/.local/bin:$PATH
          - aws s3 sync www/ s3://apspace-production/
