name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build --configuration=ci

    - name: Test
      run: yarn test --configuration=ci

    - name: E2e
      run: yarn e2e --configuration=ci
      continue-on-error: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deployment pending
      uses: deliverybot/deployment-status@master
      with:
        state: pending
        token: ${{ github.token }}

    - name: Deploy ${{ github.event.deployment.environment }}
      run: |
        echo task - ${{ github.event.deployment.task }}
        echo environment - ${{ github.event.deployment.task }}
        echo payload - ${{ github.event.deployment.payload }}

    - name: Deployment success
      if: success()
      uses: deliverybot/deployment-status@master
      with:
        state: success
        token: ${{ github.token }}

    - name: Deployment failure
      if: failure()
      uses: deliverybot/deployment-status@master
      with:
        state: failure
        token: ${{ github.token }}
